// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OmDeHoek.Model.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace OmDeHoek.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251011011910_buurten_toegevoegd")]
    partial class buurten_toegevoegd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OmDeHoek.Model.Entities.Adress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BewonerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Dorp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Huisnummer")
                        .HasColumnType("text");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Straat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BewonerId");

                    b.ToTable("Adresses");
                });

            modelBuilder.Entity("OmDeHoek.Model.Entities.Buurt", b =>
                {
                    b.Property<string>("StatistischeSectorCode")
                        .HasColumnType("text");

                    b.Property<string>("NaamDE")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NaamFR")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NaamNL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nis6DeelGemeente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NisGemeente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("StatistischeSectorCode");

                    b.HasIndex("Nis6DeelGemeente");

                    b.HasIndex("NisGemeente");

                    b.ToTable("Buurten");
                });

            modelBuilder.Entity("OmDeHoek.Model.Entities.DeelGemeente", b =>
                {
                    b.Property<string>("Nis6Code")
                        .HasColumnType("text");

                    b.Property<string>("NaamFR")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NaamNL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NisCodeGemeente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Nis6Code");

                    b.HasIndex("NisCodeGemeente");

                    b.ToTable("DeelGemeentes");
                });

            modelBuilder.Entity("OmDeHoek.Model.Entities.Gemeente", b =>
                {
                    b.Property<string>("NisCode")
                        .HasColumnType("text");

                    b.Property<string>("GesprokenTalen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NaamDE")
                        .HasColumnType("text");

                    b.Property<string>("NaamFR")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NaamNL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("NisCode");

                    b.ToTable("Gemeentes");
                });

            modelBuilder.Entity("OmDeHoek.Model.Entities.Postcode", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("NisCodeGemeente")
                        .HasColumnType("text");

                    b.HasKey("Code", "NisCodeGemeente");

                    b.HasIndex("NisCodeGemeente");

                    b.ToTable("Postcodes");
                });

            modelBuilder.Entity("OmDeHoek.Model.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("OmDeHoek.Model.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("OmDeHoek.Model.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("OmDeHoek.Model.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OmDeHoek.Model.Entities.Adress", b =>
                {
                    b.HasOne("OmDeHoek.Model.Entities.User", "Bewoner")
                        .WithMany("Adresses")
                        .HasForeignKey("BewonerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bewoner");
                });

            modelBuilder.Entity("OmDeHoek.Model.Entities.Buurt", b =>
                {
                    b.HasOne("OmDeHoek.Model.Entities.DeelGemeente", "DeelGemeente")
                        .WithMany()
                        .HasForeignKey("Nis6DeelGemeente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmDeHoek.Model.Entities.Gemeente", "Gemeente")
                        .WithMany()
                        .HasForeignKey("NisGemeente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeelGemeente");

                    b.Navigation("Gemeente");
                });

            modelBuilder.Entity("OmDeHoek.Model.Entities.DeelGemeente", b =>
                {
                    b.HasOne("OmDeHoek.Model.Entities.Gemeente", "Gemeente")
                        .WithMany()
                        .HasForeignKey("NisCodeGemeente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gemeente");
                });

            modelBuilder.Entity("OmDeHoek.Model.Entities.Postcode", b =>
                {
                    b.HasOne("OmDeHoek.Model.Entities.Gemeente", "Gemeente")
                        .WithMany()
                        .HasForeignKey("NisCodeGemeente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gemeente");
                });

            modelBuilder.Entity("OmDeHoek.Model.Entities.User", b =>
                {
                    b.Navigation("Adresses");
                });
#pragma warning restore 612, 618
        }
    }
}
